services:
  num-portal-webapp:
    container_name: num-portal-webapp
    build:
      context: https://github.com/fkaercher/num-portal-webapp.git#demo
      args:
        - env_name=dev
        - api_baseUrl=https://${BACKEND_HOST}
        - auth_baseUrl=https://${KC_HOST}
        - auth_realm=crr
        - auth_clientId=num-portal-webapp
        - legal_copyrightOwner=2024
        - welcomePageTitle_de=Willkommen
        - welcomePageTitle_en=Welcome
        - HTTP_PROXY=${HTTP_PROXY:-}
        - HTTPS_PROXY=${HTTPS_PROXY:-}
    #ports:
    #  - "4200:80"
    networks:
      num-net:
      public:
    depends_on:
      - num-portal
      - num-keycloak
    env_file:
      - path: .env
        required: false

  num-portal:
    container_name: num-portal
    build:
      dockerfile: docker/num-portal/Dockerfile
      context: .
      args:
        - http_proxy_host=${http_proxy_host:-}
        - http_proxy_port=${http_proxy_port:-}
        - https_proxy_host=${https_proxy_host:-}
        - https_proxy_port=${https_proxy_port:-}
    environment:
      spring_profiles_active: local,docker
      PORT: 8080
      DB_ADDRESS: "num-db:5432"
      DB_USER: num
      DB_PORT: num
      DB_ATT_USER: num-attachment
      DB_ATT_PORT: num-attachment
      KEYCLOAK_ADDRESS: https://${KC_HOST}
      KEYCLOAK_USER: numPortalWebapp
      KEYCLOAK_PASS: numPortalWebapp
      KEYCLOAK_CLIENT_SECRET: "czPCJDlycHGiJkrCTGUgyRV2cDs3cgxk"
      EHRBASE_ADDRESS: http://ehrbase2:8080/ehrbase/
      EHRBASE_USER: ehrbase-user
      EHRBASE_PASS: SuperSecretPassword
      URL: https://${BACKEND_HOST}
    #ports:
    #  - "8090:8080"
    networks:
      num-net:
      ehrbase-net:
      public:
    depends_on:
      - num-db
      - num-keycloak
    env_file:
      - path: .env
        required: false

  num-db:
    container_name: num-db
    build:
      dockerfile: docker/num-db/Dockerfile
      context: .
    environment:
      POSTGRES_PASSWORD: geheim
    ports:
      - "127.0.0.1:5472:5432"
    volumes:
      - num-db-data:/var/lib/postgresql/data
    networks:
      num-net:

  num-keycloak:
    container_name: num-keycloak
    build:
      context: docker/num-keycloak
      args:
        - http_proxy=${HTTP_PROXY:-}
        - https_proxy=${HTTPS_PROXY:-}
        - WEB_URL="http://localhost:4200"
        - CLIENT_SECRET="czPCJDlycHGiJkrCTGUgyRV2cDs3cgxk"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: ${KC_HOST}
      #KC_HOSTNAME_STRICT: false
      #KC_HOSTNAME_STRICT_HTTPS: false
      #KC_HTTP_ENABLED: true
    #ports:
    #  - "8100:8080"
    networks:
      num-net:
      public:
    env_file:
      - path: .env
        required: false

  ehrbase:
    container_name: ehrbase
    image: ehrbase/ehrbase:0.32.0
    environment:
      DB_URL: jdbc:postgresql://ehrbase-db:5432/ehrbase
      DB_USER: ehrbase_restricted
      DB_PASS: ehrbase_restricted
      DB_USER_ADMIN: ehrbase
      DB_PASS_ADMIN: ehrbase
      SERVER_NODENAME: local.ehrbase.org
    restart: on-failure
    ports:
      - "127.0.0.1:8070:8080"
    networks:
      ehrbase-net:
    depends_on:
      - ehrbase-db

  ehrbase-db:
    container_name:
      ehrbase-db
    image: ehrbase/ehrbase-postgres:13.4.v2
    volumes:
      - ehrbase-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      EHRBASE_USER: ehrbase_restricted
      EHRBASE_PASSWORD: ehrbase_restricted
      EHRBASE_USER_ADMIN: ehrbase
      EHRBASE_PASSWORD_ADMIN: ehrbase
    ports:
      - "127.0.0.1:5732:5432"
    networks:
      ehrbase-net:

  ehrbase2:
    container_name: ehrbase2
    image: ehrbase/ehrbase:2.6.0
    environment:
      DB_URL: jdbc:postgresql://ehrbase2-db:5432/ehrbase
      DB_USER: ehrbase_restricted
      DB_PASS: ehrbase_restricted
      DB_USER_ADMIN: ehrbase
      DB_PASS_ADMIN: ehrbase
      SERVER_NODENAME: local.ehrbase.org
      SPRING_PROFILES_ACTIVE: local
    restart: on-failure
    ports:
      - "127.0.0.1:8070:8080"
    networks:
      ehrbase-net:
    depends_on:
      - ehrbase2-db

  ehrbase2-db:
    container_name:
      ehrbase2-db
    image: ehrbase/ehrbase-v2-postgres:16.2
    volumes:
      - ehrbase2-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      PASSWORD: postgres
      EHRBASE_USER: ehrbase_restricted
      EHRBASE_PASSWORD: ehrbase_restricted
      EHRBASE_USER_ADMIN: ehrbase
      EHRBASE_PASSWORD_ADMIN: ehrbase
    ports:
      - "127.0.0.1:5732:5432"
    networks:
      ehrbase-net:
