server:
  port: ${PORT}
spring:
  datasource:
    numportal:
      url: jdbc:postgresql://${DB_ADDRESS}/numportal?currentSchema=num
      username: ${DB_USER}
      password: ${DB_PORT}
    numportal-attachment:
      url: jdbc:postgresql://${DB_ADDRESS}/num-attachment?currentSchema=num
      username: ${DB_ATT_USER}
      password: ${DB_ATT_PORT}
  security:
    oauth2:
      client:
        registration:
          userStoreClient:
            client-secret: ${KEYCLOAK_CLIENT_SECRET}

keycloak:
  url: ${KEYCLOAK_ADDRESS}

swagger:
  oauth2:
    client-name: ${KEYCLOAK_USER}
    client-secret: ${KEYCLOAK_PASS}

ehrbase:
  rest-api-url: ${EHRBASE_ADDRESS}
  username: ${EHRBASE_USER}
  password: ${EHRBASE_PASS}

num:
  url: ${URL}
