
-- create user --
CREATE ROLE "num" WITH LOGIN PASSWORD 'num';

-- create database --
CREATE DATABASE "numportal" WITH OWNER = 'num' ENCODING = 'UTF8' CONNECTION LIMIT = -1;
GRANT ALL PRIVILEGES ON DATABASE "numportal" TO "num";

\c numportal
CREATE SCHEMA IF NOT EXISTS num AUTHORIZATION "num";
GRANT  ALL PRIVILEGES  ON SCHEMA num  TO "num";
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES ON ALL TABLES IN SCHEMA num TO "num";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA num TO "num";
GRANT  ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA  num  TO "num";
